### ISSUE TITLE
A session had already been started 

### ISSUE THREAD

**Issue by inos-github** [SecSign/SecSign-ID-Nextcloud-Plugin#10]
nextcloud 18.0.3
SecSign-ID app 0.3.1
PHP  7.3.16 

'memcache.local' => '\\OC\\Memcache\\APCu',
'memcache.locking' => '\\OC\\Memcache\\Redis',

"app":"PHP","method":"GET","url":"/login/challenge/secsignid","message":"session_start(): A session had already been started - ignoring at [...]/nextcloud/apps/secsignid/templates/login/authentication.php#9"

Please let me know in case you are needing some more information

**Comment by secsignid** [comment]
Hi,
This looks to be an issue regarding your SecSign ID. This occurs when you begin SecSign ID authentication on some service or device and do not complete the process before trying again. To fix this, simply open your SecSign ID app and choose to either authenticate or cancel the existing session, then try again. We will work on making this clearer to the user with an error message. Did this cause a crash?

Greetings,
The SecSign Team

**Comment by inos-github** [comment]
HI,
Thank you for your prompt reply!
The SecSign App is installed and linked to my account on an Android device as well as on an iOS device. There is no open authentication request.
Starting a new authentication triggers the app on iOS but not on Android. As soon as the Android app is opened manually, the authentication process starts and the pictogram is displayed - so it's working. However, the app (Android) shows a message that there is no login request pending, this message does not showup on the iOS device.
The error message is logged on every login event.
So probably the error is caused because of using two devices for authentication?

**Comment by secsignid** [comment]
Thank you for the information!

Are you attempting to authenticate the same request on both phones? When exactly does the message you mentioned on the Android phone occur? Please include screenshots if possible.

Having the same ID on multiple devices is fully intended and should not lead to any difficulties. Each authentication request can only be answered by one device though as the request is discarded once it has been answered once.

**Comment by inos-github** [comment]
> Starting a new authentication triggers the app on iOS but not on Android. As soon as the Android app is opened manually, the authentication process starts and the pictogram is displayed

this only happens sometimes and is not  reproducible.


> app":"PHP","method":"GET","url":"/login/challenge/secsignid","message":"session_start(): A session had already been started - ignoring at [...]/nextcloud/apps/secsignid/templates/login/authentication.php#9"

this error is still logged each time I'm using SecSign as the second factor. I'm running nextcloud behind a reverse proxy (caddy) - could that setup be the cause for this error?

**Comment by secsignid** [comment]
Hi,
The error regarding the 'session' seems to be caused by the creation of a browser session variable while one already exists and has nothing to do with your SecSign ID or the authentication process as we had initially assumed. This should have no effect on the functionality but we will be addressing it as soon as possible.
At the moment we are not sure what may be causing the other issue but we will notify you once anything has changed.
Thanks again for your feedback! If you enjoy using our app (or don't), please feel free to leave a review in the [Nextcloud app store](https://apps.nextcloud.com/apps/secsignid).

Greetings,
The SecSign Team
