### ISSUE TITLE
Can't install or update (0.1.1 to 0.1.2)

### ISSUE THREAD

**Issue by Guibock** [SecSign/SecSign-ID-Nextcloud-Plugin#2]
Was giving another try today.
No more luck this time.

I have got another error message saying : 
> There is no column with name 'id' on table 'oc_secsignid'

![secsignid](https://user-images.githubusercontent.com/24889988/54128714-f0b1ef00-440c-11e9-8410-f10b5ef0fb57.jpg)

**Comment by secsignid** [comment]
Hi,

Sorry for the inconvenience. The app has been updated to 0.1.3. This update should contain a fix for your issue. If you are still having issues, please try reinstalling the app.
Thank you very much for your feedback.

Greetings,
The SecSign team.

**Comment by Guibock** [comment]
Hello SecSign team,
I removed the SecSign app from the App list on my Nextcloud instance.
Then, I clicked "Install and activate" but no more luck this time, there is another error message :

App with id secsignid has invalid signature
(Image below)

Greetings,
Guillaume.

**Comment by Guibock** [comment]
![capture 2019-03-18 à 16 28](https://user-images.githubusercontent.com/24889988/54542096-6bde4c80-499b-11e9-9c5f-eaa24591bc63.jpg)

**Comment by secsignid** [comment]
Hi,

Please check out the newest version of the app (0.2.0). It has been updated to fix the issues you were having and now also features a new design and more administrative options. Thank you very much for your feedback.

Greetings,
The SecSign Team
