### ISSUE TITLE
Error 500 when enabled

### ISSUE THREAD

**Issue by TimP4w** [SecSign/SecSign-ID-Nextcloud-Plugin#3]
Nextcloud version: 15.0.7

When I enable the plugin, I get an Error 500 message from the browser, but it works flawlessly from the app (Android). 

Log:

Error | PHP | Declaration of OCA\SecSignID\Provider\SecSign2FA::verifyChallenge(OCP\IUser $user, $challenge): bool must be compatible with OCP\Authentication\TwoFactorAuth\IProvider::verifyChallenge(OCP\IUser $user, string $challenge): bool at /var/www/nextcloud/apps/secsignid/lib/Provider/SecSign2FA.php#23
-- | -- | --

**Comment by secsignid** [comment]
Hi,

Thanks for your feedback. We could not reproduce this issue but changes have been made that should address it. These changes are available in the newest version (0.2.1). If you continue to have any issues with this, feel free to contact us here or at [support@secsign.com](mailto:support@secsign.com).

Greetings,
The SecSign Team
