### ISSUE TITLE
Upgrade to Nextcloud 16 !

### ISSUE THREAD

**Issue by Dragofafmir** [SecSign/SecSign-ID-Nextcloud-Plugin#4]
Please update the app to nextcloud 16 :) ! 
Thanks in advance !

**Comment by secsignid** [comment]
Hi,

The App has now been updated to Version 0.2.0 with support for NextCloud 16. It also includes a visual overhaul and a few added administrative options. If you have any issues, please feel free to contact us here or at [support@secsign.com](mailto:support@secsign.com).

Greetings,
The SecSign team.

**Comment by Dragofafmir** [comment]
Many thanks 😃 !
