### ISSUE TITLE
Can't activate SecSign for user

### ISSUE THREAD

**Issue by davodego** [SecSign/SecSign-ID-Nextcloud-Plugin#5]
Hello,
I followed the steps at https://www.secsign.com/developers/nextcloud-two-factor-authentication-plugin-secsign but on settings page in section "SecSign 2FA" I see the message "SecSign 2FA is currently not set up for this account. Contact your administrator for more information".
I'am the admin of this page and I cant find the issue. 

Nextcloud 16.0.4
Server Ubuntu 18.04

**Comment by secsignid** [comment]
Hi,
Thanks for your feedback. Version 0.2.4 should address the issue you were experiencing. If your issue persists, feel free to message us here or at [support@secsign.com](mailto:support@secsign.com).

Greetings,
The SecSign Team
