### ISSUE TITLE
Nextcloud says some files could not be verified

### ISSUE THREAD

**Issue by Ninj1zz** [SecSign/SecSign-ID-Nextcloud-Plugin#8]
Hello there,
since today I'm experiencing an issue with SecSign. Nextcloud says that some files and the signature of secsignid could get verified. My problem is that I really have no idea how to fix this error. 
The error message is the following:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.
Results
=======
- secsignid
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature could not get verified.
Raw output
==========
Array
(
    [secsignid] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature could not get verified.
                )
        )
)

**Comment by secsignid** [comment]
Hi,
Sorry that you are experiencing this issue. We haven't been able to replicate this, could you please specify which NextCloud version and which version of our app you are using?

Greetings,
The SecSign Team

**Comment by inos-github** [comment]
I had the same after the upgrade from NC 18.0.2 to 18.0.3.
I've deleted/removed the app and installed it again without any issue.

**Comment by secsignid** [comment]
Just to clarify: Is it working for you now? If not, please try installing the latest update (0.3.1) to see if the issue persists.

**Comment by Csubi76** [comment]
Upgrade NC 18.0.3 to 18.0.4. 
I get the same message.
Deleting and then installing solved it for me too.

**Comment by secsignid** [comment]
Hi,
Thanks for the feedback, we'll have a look at what may be causing this issue. If you enjoy the app, please consider giving us a rating [in the Nextcloud app store](https://apps.nextcloud.com/apps/secsignid).

Greetings,
The SecSign Team

**Comment by inos-github** [comment]
After updating nextcloud to 18.0.5, the same failure is logged
```
Results ======= 
- secsignid 	- EXCEPTION 		- OC\IntegrityCheck\Exceptions\InvalidSignatureException 		
- Signature could not get verified. 
```

**Comment by Csubi76** [comment]
18.0.6,
18.0.7
this is an error with every update.

What's the problem?
When will it be repaired?

**Comment by secsignid** [comment]
Hi,

thanks for the notice. We are working on this. This warning is a false error because of a bug in the NextCloud updater. The signature is fine and the plugin still works without any problems. You can either reinstall the plugin to remove the warning or just ignore it.

Greetings,
The SecSign Team
