### ISSUE TITLE
Nextcloud 18

### ISSUE THREAD

**Issue by inos-github** [SecSign/SecSign-ID-Nextcloud-Plugin#9]
HI,
could you please update for Nextcloud 18

Thank's for the App!

**Comment by secsignid** [comment]
Hi,
Thanks for addressing this. Version 0.3.1 is now live and should work fine with NextCloud18. If you run into any issues feel free to contact us here or at [support@secsign.com](mailto:support@secsign.com).
Greetings,
The SecSign Team

**Comment by inos-github** [comment]
Thank's for the update!
It's working however I'm experiencing an error in the log but I will open a new issue about this.
